import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/next';
import { site } from '@/config/site';
import './globals.css';

// TODO /setup: import project fonts from next/font/google based on brand.md Typography section
// Example:
//   import { Inter } from 'next/font/google';
//   const inter = Inter({ subsets: ['latin'], variable: '--font-heading' });
// Then add the variable className to <html> and 'font-heading' to <body>

export const metadata: Metadata = {
  title: site.ogTitle,
  description: site.description,
  // icon-light.png / icon-dark.png are wired here rather than relying on the
  // app/icon.png file convention so the browser picks the right one per color scheme.
  // Generated by /assets -- re-run if the logomark changes.
  // Only needed when /assets runs in DUAL or AUTO mode (see assets prompt step 6).
  // If SINGLE mode (colored mark), remove this block -- app/icon.png handles it.
  icons: {
    icon: [
      { url: '/icon-light.png', media: '(prefers-color-scheme: light)' },
      { url: '/icon-dark.png', media: '(prefers-color-scheme: dark)' },
    ],
  },
  openGraph: {
    title: site.ogTitle,
    description: site.ogDescription ?? site.description,
    url: site.url,
    siteName: site.name,
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: site.ogTitle,
    description: site.ogDescription ?? site.description,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // TODO /setup: add font variable className(s) to <html> once fonts are configured above
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  );
}